export interface Product {
  id: number
  title: string
  category: string
  subcategory: string
  brand: string
  store: string
  storeDistance: string
  originalPrice: number
  discountPrice: number
  discountPercent: number
  image: string
  isFlash: boolean
  flashEnd?: string
  location: string
}

export interface Category {
  id: number
  name: string
  icon: string
  count: number
}

export interface Store {
  id: number
  name: string
  category: string
  location: string
  activePromos: number
  image: string
  logoInitial: string
  logoColor: string
  logoGradient: string
}

export const categories: Category[] = [
  { id: 1, name: "Supermarchés", icon: "🛒", count: 1240 },
  { id: 2, name: "Mode", icon: "👗", count: 892 },
  { id: 3, name: "Chaussures", icon: "👟", count: 412 },
  { id: 4, name: "Beauté", icon: "💄", count: 356 },
  { id: 5, name: "Téléphones", icon: "📱", count: 289 },
  { id: 6, name: "Informatique", icon: "💻", count: 174 },
  { id: 7, name: "Électroménager", icon: "🔌", count: 246 },
  { id: 8, name: "Restaurants", icon: "🍽️", count: 512 },
  { id: 9, name: "Pharmacies", icon: "💊", count: 138 },
  { id: 10, name: "Automobile", icon: "🚗", count: 92 },
  { id: 11, name: "Mobilier", icon: "🛋️", count: 156 },
  { id: 12, name: "Sport", icon: "⚽", count: 201 },
]

export const flashProducts: Product[] = [
  {
    id: 1,
    title: "Riz parfumé Basmati 25kg",
    category: "Supermarchés",
    subcategory: "Alimentation",
    brand: "Tilda",
    store: "Casino Brazza",
    storeDistance: "1.2 km",
    originalPrice: 42000,
    discountPrice: 28900,
    discountPercent: 31,
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&q=70&auto=format",
    isFlash: true,
    flashEnd: "05:59:59",
    location: "Brazzaville",
  },
  {
    id: 2,
    title: "Smartphone Galaxy A15 128Go",
    category: "Téléphones",
    subcategory: "Mobiles",
    brand: "Samsung",
    store: "TechCongo",
    storeDistance: "0.8 km",
    originalPrice: 165000,
    discountPrice: 129000,
    discountPercent: 22,
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&q=70&auto=format",
    isFlash: true,
    flashEnd: "01:59:59",
    location: "Brazzaville",
  },
  {
    id: 3,
    title: "Poulet braisé + attiéké + boisson",
    category: "Restaurants",
    subcategory: "Plats",
    brand: "Chez Mama",
    store: "Chez Mama Poto-Poto",
    storeDistance: "0.4 km",
    originalPrice: 6500,
    discountPrice: 3900,
    discountPercent: 40,
    image: "https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=600&q=70&auto=format",
    isFlash: true,
    flashEnd: "05:59:59",
    location: "Brazzaville",
  },
  {
    id: 16,
    title: "Huile végétale premium 5L",
    category: "Supermarchés",
    subcategory: "Alimentation",
    brand: "Cana",
    store: "Super U Congo",
    storeDistance: "2.3 km",
    originalPrice: 12500,
    discountPrice: 8900,
    discountPercent: 29,
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&q=70&auto=format",
    isFlash: true,
    flashEnd: "03:29:59",
    location: "Brazzaville",
  },
  {
    id: 17,
    title: "iPhone 14 128Go - Étui offert",
    category: "Téléphones",
    subcategory: "Mobiles",
    brand: "Apple",
    store: "TechCongo",
    storeDistance: "0.8 km",
    originalPrice: 780000,
    discountPrice: 649000,
    discountPercent: 17,
    image: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=600&q=70&auto=format",
    isFlash: true,
    flashEnd: "02:14:59",
    location: "Brazzaville",
  },
  {
    id: 26,
    title: "Café moulu premium 1kg",
    category: "Supermarchés",
    subcategory: "Alimentation",
    brand: "Lavazza",
    store: "Casino Brazza",
    storeDistance: "1.2 km",
    originalPrice: 18500,
    discountPrice: 12900,
    discountPercent: 30,
    image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=600&q=70&auto=format",
    isFlash: true,
    flashEnd: "04:45:59",
    location: "Brazzaville",
  },
  {
    id: 27,
    title: "Tablette Samsung Tab A9",
    category: "Téléphones",
    subcategory: "Tablettes",
    brand: "Samsung",
    store: "TechCongo",
    storeDistance: "0.8 km",
    originalPrice: 195000,
    discountPrice: 159000,
    discountPercent: 18,
    image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&q=70&auto=format",
    isFlash: true,
    flashEnd: "01:30:59",
    location: "Brazzaville",
  },
  {
    id: 28,
    title: "Sandales cuir homme",
    category: "Chaussures",
    subcategory: "Sandales",
    brand: "Prestige",
    store: "Fashion Hub",
    storeDistance: "3.8 km",
    originalPrice: 45000,
    discountPrice: 29900,
    discountPercent: 34,
    image: "https://images.unsplash.com/photo-1603487742131-4160ec999306?w=600&q=70&auto=format",
    isFlash: true,
    flashEnd: "06:15:59",
    location: "Pointe-Noire",
  },
]

export const todayProducts: Product[] = [
  {
    id: 4,
    title: "Riz parfumé Basmati 25kg",
    category: "Supermarchés",
    subcategory: "Alimentation",
    brand: "Tilda",
    store: "Casino Brazza",
    storeDistance: "1.2 km",
    originalPrice: 42000,
    discountPrice: 28900,
    discountPercent: 31,
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&q=70&auto=format",
    isFlash: true,
    flashEnd: "05:59:59",
    location: "Brazzaville",
  },
  {
    id: 5,
    title: "Sneakers running homme",
    category: "Chaussures",
    subcategory: "Sneakers",
    brand: "Nike Revolution",
    store: "SportZone",
    storeDistance: "3.4 km",
    originalPrice: 85000,
    discountPrice: 54900,
    discountPercent: 35,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=70&auto=format",
    isFlash: false,
    location: "Brazzaville",
  },
  {
    id: 6,
    title: "Smartphone Galaxy A15 128Go",
    category: "Téléphones",
    subcategory: "Mobiles",
    brand: "Samsung",
    store: "TechCongo",
    storeDistance: "0.8 km",
    originalPrice: 165000,
    discountPrice: 129000,
    discountPercent: 22,
    image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&q=70&auto=format",
    isFlash: true,
    flashEnd: "01:59:59",
    location: "Brazzaville",
  },
  {
    id: 7,
    title: "Robe wax coupe moderne",
    category: "Mode",
    subcategory: "Prêt-à-porter",
    brand: "Atelier Nzinga",
    store: "Nzinga Store",
    storeDistance: "2.1 km",
    originalPrice: 35000,
    discountPrice: 21900,
    discountPercent: 37,
    image: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=600&q=70&auto=format",
    isFlash: false,
    location: "Brazzaville",
  },
  {
    id: 8,
    title: "Télé LED 55\" 4K UHD",
    category: "Électroménager",
    subcategory: "Téléviseurs",
    brand: "LG",
    store: "MaxiElec",
    storeDistance: "5.7 km",
    originalPrice: 480000,
    discountPrice: 349000,
    discountPercent: 27,
    image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=600&q=70&auto=format",
    isFlash: false,
    location: "Pointe-Noire",
  },
  {
    id: 9,
    title: "Poulet braisé + attiéké + boisson",
    category: "Restaurants",
    subcategory: "Plats",
    brand: "Chez Mama",
    store: "Chez Mama Poto-Poto",
    storeDistance: "0.4 km",
    originalPrice: 6500,
    discountPrice: 3900,
    discountPercent: 40,
    image: "https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=600&q=70&auto=format",
    isFlash: true,
    flashEnd: "05:59:59",
    location: "Brazzaville",
  },
  {
    id: 10,
    title: "Fond de teint peaux noires",
    category: "Beauté",
    subcategory: "Maquillage",
    brand: "Fenty Beauty",
    store: "Glow Cosmetics",
    storeDistance: "1.9 km",
    originalPrice: 28000,
    discountPrice: 19600,
    discountPercent: 30,
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=70&auto=format",
    isFlash: false,
    location: "Brazzaville",
  },
  {
    id: 11,
    title: "Ordinateur portable 15\" i5",
    category: "Informatique",
    subcategory: "Ordinateurs",
    brand: "HP Pavilion",
    store: "TechCongo",
    storeDistance: "0.8 km",
    originalPrice: 520000,
    discountPrice: 429000,
    discountPercent: 17,
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&q=70&auto=format",
    isFlash: false,
    location: "Brazzaville",
  },
  {
    id: 12,
    title: "Canapé 3 places cuir synthétique",
    category: "Mobilier",
    subcategory: "Salon",
    brand: "Home Congo",
    store: "MaisonPlus",
    storeDistance: "4.1 km",
    originalPrice: 380000,
    discountPrice: 269000,
    discountPercent: 29,
    image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=70&auto=format",
    isFlash: false,
    location: "Brazzaville",
  },
  {
    id: 13,
    title: "Ballon de foot Adidas officiel",
    category: "Sport",
    subcategory: "Football",
    brand: "Adidas",
    store: "SportZone",
    storeDistance: "3.4 km",
    originalPrice: 25000,
    discountPrice: 15900,
    discountPercent: 36,
    image: "https://images.unsplash.com/photo-1614632537190-d0448c1b7e2f?w=600&q=70&auto=format",
    isFlash: false,
    location: "Brazzaville",
  },
  {
    id: 14,
    title: "Kit anti-âge complet",
    category: "Beauté",
    subcategory: "Soins",
    brand: "Dior",
    store: "Glow Cosmetics",
    storeDistance: "1.9 km",
    originalPrice: 95000,
    discountPrice: 64900,
    discountPercent: 32,
    image: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&q=70&auto=format",
    isFlash: false,
    location: "Brazzaville",
  },
  {
    id: 15,
    title: "Serviettes de bain 3 pièces",
    category: "Mobilier",
    subcategory: "Salle de bain",
    brand: "Prestige",
    store: "MaisonPlus",
    storeDistance: "4.1 km",
    originalPrice: 18000,
    discountPrice: 11900,
    discountPercent: 34,
    image: "https://images.unsplash.com/photo-1616627990321-1a7e7b3b8d1a?w=600&q=70&auto=format",
    isFlash: false,
    location: "Brazzaville",
  },
  {
    id: 18,
    title: "Veste cuir synthétique homme",
    category: "Mode",
    subcategory: "Prêt-à-porter",
    brand: "FashionPoint",
    store: "Nzinga Store",
    storeDistance: "2.1 km",
    originalPrice: 65000,
    discountPrice: 39900,
    discountPercent: 39,
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&q=70&auto=format",
    isFlash: false,
    location: "Brazzaville",
  },
  {
    id: 19,
    title: "Pack couches bébé 4x4",
    category: "Supermarchés",
    subcategory: "Bébé",
    brand: "SoftCare",
    store: "Super U Congo",
    storeDistance: "2.3 km",
    originalPrice: 32000,
    discountPrice: 22900,
    discountPercent: 28,
    image: "https://images.unsplash.com/photo-1594942464923-91004878898d?w=600&q=70&auto=format",
    isFlash: false,
    location: "Brazzaville",
  },
  {
    id: 20,
    title: "Robe de soirée à paillettes",
    category: "Mode",
    subcategory: "Prêt-à-porter",
    brand: "Atelier Nzinga",
    store: "Nzinga Store",
    storeDistance: "2.1 km",
    originalPrice: 55000,
    discountPrice: 34900,
    discountPercent: 37,
    image: "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=600&q=70&auto=format",
    isFlash: false,
    location: "Brazzaville",
  },
  {
    id: 21,
    title: "Climatiseur split 12000 BTU",
    category: "Électroménager",
    subcategory: "Climatisation",
    brand: "Samsung",
    store: "MaxiElec",
    storeDistance: "5.7 km",
    originalPrice: 420000,
    discountPrice: 319000,
    discountPercent: 24,
    image: "https://images.unsplash.com/photo-1631545806609-3c480d65e0c8?w=600&q=70&auto=format",
    isFlash: false,
    location: "Pointe-Noire",
  },
  {
    id: 22,
    title: "Pull en laine mérinos",
    category: "Mode",
    subcategory: "Prêt-à-porter",
    brand: "Zegna",
    store: "Fashion Hub",
    storeDistance: "3.8 km",
    originalPrice: 120000,
    discountPrice: 79000,
    discountPercent: 34,
    image: "https://images.unsplash.com/photo-1434389677669-e08b4cda3797?w=600&q=70&auto=format",
    isFlash: false,
    location: "Brazzaville",
  },
  {
    id: 23,
    title: "Jus de fruits bio 6x1L",
    category: "Supermarchés",
    subcategory: "Boissons",
    brand: "Tropicana",
    store: "Casino Brazza",
    storeDistance: "1.2 km",
    originalPrice: 14500,
    discountPrice: 9900,
    discountPercent: 32,
    image: "https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=600&q=70&auto=format",
    isFlash: false,
    location: "Brazzaville",
  },
  {
    id: 24,
    title: "Table basse design en métal",
    category: "Mobilier",
    subcategory: "Salon",
    brand: "Home Congo",
    store: "MaisonPlus",
    storeDistance: "4.1 km",
    originalPrice: 195000,
    discountPrice: 139000,
    discountPercent: 29,
    image: "https://images.unsplash.com/photo-1532372320572-cda25653a26d?w=600&q=70&auto=format",
    isFlash: false,
    location: "Brazzaville",
  },
  {
    id: 25,
    title: "Ordinateur portable gamer 15.6\"",
    category: "Informatique",
    subcategory: "Ordinateurs",
    brand: "Dell G15",
    store: "TechCongo",
    storeDistance: "0.8 km",
    originalPrice: 980000,
    discountPrice: 749000,
    discountPercent: 24,
    image: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=600&q=70&auto=format",
    isFlash: false,
    location: "Brazzaville",
  },
  {
    id: 29,
    title: "Perruque synthétique afro",
    category: "Beauté",
    subcategory: "Accessoires",
    brand: "Glow Beauty",
    store: "Glow Cosmetics",
    storeDistance: "1.9 km",
    originalPrice: 45000,
    discountPrice: 29900,
    discountPercent: 34,
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=70&auto=format",
    isFlash: false,
    location: "Brazzaville",
  },
  {
    id: 30,
    title: "Machine à laver 8kg",
    category: "Électroménager",
    subcategory: "Lavage",
    brand: "LG",
    store: "MaxiElec",
    storeDistance: "5.7 km",
    originalPrice: 520000,
    discountPrice: 389000,
    discountPercent: 25,
    image: "https://images.unsplash.com/photo-1582738411706-bfc8e691d1c2?w=600&q=70&auto=format",
    isFlash: false,
    location: "Pointe-Noire",
  },
  {
    id: 31,
    title: "Escarpins femme 9cm",
    category: "Chaussures",
    subcategory: "Escarpins",
    brand: "Fashion Step",
    store: "Fashion Hub",
    storeDistance: "3.8 km",
    originalPrice: 55000,
    discountPrice: 34900,
    discountPercent: 37,
    image: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&q=70&auto=format",
    isFlash: false,
    location: "Brazzaville",
  },
  {
    id: 32,
    title: "Assurance auto 12 mois",
    category: "Automobile",
    subcategory: "Assurance",
    brand: "NSIA",
    store: "NSIA Brazza",
    storeDistance: "2.5 km",
    originalPrice: 180000,
    discountPrice: 135000,
    discountPercent: 25,
    image: "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=600&q=70&auto=format",
    isFlash: false,
    location: "Brazzaville",
  },
  {
    id: 33,
    title: "Pack 12 gélules magnésium",
    category: "Pharmacies",
    subcategory: "Compléments",
    brand: "Arkopharma",
    store: "Pharma Congo",
    storeDistance: "1.1 km",
    originalPrice: 12000,
    discountPrice: 8500,
    discountPercent: 29,
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=70&auto=format",
    isFlash: false,
    location: "Brazzaville",
  },
  {
    id: 34,
    title: "Sac à dos cuir synthétique",
    category: "Mode",
    subcategory: "Accessoires",
    brand: "FashionPoint",
    store: "Nzinga Store",
    storeDistance: "2.1 km",
    originalPrice: 35000,
    discountPrice: 21900,
    discountPercent: 37,
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=70&auto=format",
    isFlash: false,
    location: "Brazzaville",
  },
  {
    id: 35,
    title: "Crème hydratante corps",
    category: "Beauté",
    subcategory: "Soins",
    brand: "Nivea",
    store: "Pharma Congo",
    storeDistance: "1.1 km",
    originalPrice: 8500,
    discountPrice: 5900,
    discountPercent: 31,
    image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600&q=70&auto=format",
    isFlash: false,
    location: "Brazzaville",
  },
  {
    id: 36,
    title: "Lunettes de soleil aviateur",
    category: "Mode",
    subcategory: "Accessoires",
    brand: "Ray-Ban",
    store: "Fashion Hub",
    storeDistance: "3.8 km",
    originalPrice: 95000,
    discountPrice: 64900,
    discountPercent: 32,
    image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&q=70&auto=format",
    isFlash: false,
    location: "Brazzaville",
  },
]

export const allProducts: Product[] = [...flashProducts, ...todayProducts]

export const stores: Store[] = [
  { id: 1, name: "Casino Brazza", category: "🏬", location: "Brazzaville", activePromos: 42, image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&q=70&auto=format", logoInitial: "CB", logoColor: "text-white", logoGradient: "bg-gradient-to-br from-red-600 to-red-500" },
  { id: 2, name: "SportZone", category: "⚽", location: "Pointe-Noire", activePromos: 18, image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=70&auto=format", logoInitial: "SZ", logoColor: "text-white", logoGradient: "bg-gradient-to-br from-emerald-600 to-teal-500" },
  { id: 3, name: "TechCongo", category: "📱", location: "Brazzaville", activePromos: 27, image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&q=70&auto=format", logoInitial: "TC", logoColor: "text-white", logoGradient: "bg-gradient-to-br from-blue-600 to-cyan-500" },
  { id: 4, name: "Nzinga Store", category: "👗", location: "Brazzaville", activePromos: 12, image: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=600&q=70&auto=format", logoInitial: "NS", logoColor: "text-white", logoGradient: "bg-gradient-to-br from-fuchsia-600 to-pink-500" },
  { id: 5, name: "MaxiElec", category: "🔌", location: "Pointe-Noire", activePromos: 33, image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=600&q=70&auto=format", logoInitial: "ME", logoColor: "text-white", logoGradient: "bg-gradient-to-br from-slate-600 to-zinc-500" },
  { id: 6, name: "Glow Cosmetics", category: "💄", location: "Brazzaville", activePromos: 21, image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&q=70&auto=format", logoInitial: "GC", logoColor: "text-white", logoGradient: "bg-gradient-to-br from-rose-600 to-pink-500" },
  { id: 7, name: "Super U Congo", category: "🛒", location: "Brazzaville", activePromos: 56, image: "https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=600&q=70&auto=format", logoInitial: "SU", logoColor: "text-white", logoGradient: "bg-gradient-to-br from-indigo-600 to-violet-500" },
  { id: 8, name: "MaisonPlus", category: "🛋️", location: "Brazzaville", activePromos: 15, image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=70&auto=format", logoInitial: "MP", logoColor: "text-white", logoGradient: "bg-gradient-to-br from-amber-600 to-yellow-500" },
  { id: 9, name: "Fashion Hub", category: "👠", location: "Pointe-Noire", activePromos: 24, image: "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=600&q=70&auto=format", logoInitial: "FH", logoColor: "text-white", logoGradient: "bg-gradient-to-br from-violet-600 to-indigo-500" },
  { id: 10, name: "Pharma Congo", category: "💊", location: "Brazzaville", activePromos: 31, image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=70&auto=format", logoInitial: "PC", logoColor: "text-white", logoGradient: "bg-gradient-to-br from-teal-600 to-green-500" },
  { id: 11, name: "NSIA Brazza", category: "🛡️", location: "Brazzaville", activePromos: 8, image: "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=600&q=70&auto=format", logoInitial: "NS", logoColor: "text-white", logoGradient: "bg-gradient-to-br from-slate-700 to-blue-800" },
  { id: 12, name: "Chez Mama Poto-Poto", category: "🍽️", location: "Brazzaville", activePromos: 9, image: "https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=600&q=70&auto=format", logoInitial: "CM", logoColor: "text-white", logoGradient: "bg-gradient-to-br from-orange-600 to-amber-500" },
]
